export {default as Discover} from "./Discover/Discover"
export {default as Feelthemusic} from "./Landing/Feelthemusic"
export {default as Footer} from "./Footer/Footer"
export {default as Navbar} from "./NavBar/Navbar"
export {default as Join} from "./Register/Join"