export {default as Discover} from "./Discover"
export {default as Feelthemusic} from "./Feelthemusic"
export {default as Footer} from "./Footer"
export {default as Navbar} from "./Navbar"
export {default as Join} from "./Join"